---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: {{.kube_namespace}}
data:
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  KAFKA_ZOOKEEPER_CONNECT: "{{ .zookeeper_host }}:2181"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-shared
  namespace: {{.kube_namespace}}
data:
  KAFKA_BOOTSTRAP_SERVERS: {{.kafka_host}}:9092
  KAFKA_HOST: {{.kafka_host}}:9092
  KAFKA_TOPIC_SUFFIX: {{.env_prefix}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: {{.kube_namespace}}
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
{{ if .gke_nodepool }}
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .gke_nodepool }}
{{ end }}
      initContainers:
      - name: kafka-init
        image: {{ .init_docker_image }}
        command: ["sh", "-c", "until nc -z -w2 {{ .zookeeper_host }} 2181; do sleep 2s; done"]
      containers:
      - name: kafka
        image: {{ .kafka_docker_image }}
        envFrom:
        - configMapRef:
            name: kafka-config
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        command:
        - sh
        - -c
        - |
          unset KAFKA_PORT && \
          export KAFKA_ADVERTISED_HOST_NAME=${POD_IP} && \
          export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${POD_IP}:9092 && \
          export KAFKA_BROKER_ID=${HOSTNAME##*-} && \
          export KAFKA_LOG_DIRS=/opt/kafka/data && \
          /etc/confluent/docker/run
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 9092
          timeoutSeconds: 5
        ports:
        - containerPort: 9092
        readinessProbe:
          exec:
            command:
            - kafka-topics
            - --zookeeper
            - {{ .zookeeper_host }}:2181
            - --list
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: {{ .kafka_cpu }}
            memory: {{ .kafka_mem }}
        volumeMounts:
        - name: kafka-claim-{{.kube_namespace}}
          mountPath: /opt/kafka/data
          subPath: kafka
  volumeClaimTemplates:
  - metadata:
      name: kafka-claim-{{.kube_namespace}}
      annotations:
        #volume.beta.kubernetes.io/storage-class: {{ .storage_class_name }}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .kafka_disk }}
      selector:
        matchLabels:
           app: ota
           id: ota-kafka-pv-{{.kube_namespace}}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: {{.kube_namespace}}
spec:
  ports:
  - port: 9092
  selector:
    app: kafka
