---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{.kube_namespace}}
data:
  AUTH_PLUS_HOST: auth-plus
  AUTH_PLUS_PORT: '80'
  AUTH_PROTOCOL: none
  AUTH_VERIFICATION: local
  CAMPAIGNER_HOST: campaigner
  CAMPAIGNER_PORT: '80'
  CRYPT_CREATE_ACCOUNTS: "false"
  DEVICE_GATEWAY_PORT: '8000'
  DEVICE_REGISTRY_HOST: device-registry
  DEVICE_REGISTRY_PORT: '80'
  DIRECTOR_HOST: director
  DIRECTOR_PORT: '80'
  ENV_PREFIX: {{ .env_prefix }}
  JAVA_OPTS: {{ .app_java_opts }}
  MESSAGING_MODE: kafka
  OIDC_LOGIN_ACTION: com.advancedtelematic.auth.garage.NoLoginAction
  OIDC_LOGOUT_ACTION: com.advancedtelematic.auth.garage.NoLogoutAction
  OIDC_NS_PROVIDER: com.advancedtelematic.auth.oidc.ConfiguredNamespace
  OIDC_TOKEN_EXCHANGE: com.advancedtelematic.auth.NoExchange
  OIDC_TOKEN_VERIFICATION: com.advancedtelematic.auth.oidc.TokenValidityCheck
  PACKAGES_VERSION_FORMAT: ".+"
  PLAY_HTTP_SESSION_SECURE: 'false'
  REPORT_METRICS: "false"
  SOTA_CORE_HOST: sota-core
  SOTA_CORE_PORT: '80'
  TREEHUB_HOST_PUB: treehub.{{ .ingress_dns_name }}
  TREEHUB_PORT_PUB: '80'
  TOGGLE_ATS_GARAGE_THEME: "false"
  TOGGLE_AUTO_FEATURE_ACTIVATION: "false"
  TOGGLE_CREDENTIALS_DOWNLOAD: "false"
  TOGGLE_PREBUILT_DEBRPM: "false"
  TOGGLE_USER_PROFILE_MENU: "false"
  TUF_REPOSERVER_HOST: tuf-reposerver
  TUF_REPOSERVER_PORT: '80'
  TUF_REPOSERVER_HOST_PUB: tuf-reposerver.{{.ingress_dns_name}}
  TUF_REPOSERVER_PORT_PUB: '80'
  WS_HOST: web-events.{{ .ingress_dns_name }}
  WS_PORT: '80'
  WS_SCHEME: ws
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: {{.kube_namespace}}
spec:
  selector:
    matchLabels:
      app: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app
    spec:
{{ if .gke_nodepool }}
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .gke_nodepool }}
{{ end }}
      containers:
      - image: {{ .app_docker_image }}
        name: app
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
        args:
        - "-Dhttp.port=9001"
        - "-Dwebsrc.atsgarage=ws://*.{{ .ingress_dns_name }}:80"
        envFrom:
        - configMapRef:
            name: kafka-shared
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret
        resources:
          requests:
            cpu: {{ .app_cpu }}
            memory: {{ .app_mem }}
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 30
          httpGet:
            port: 9001
            path: "/health"
---
{{- if .create_ingress }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app
  namespace: {{.kube_namespace}}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/limit-whitelist: {{.ingress_acl_whitelist}}
    nginx.ingress.kubernetes.io/proxy-body-size: {{.ingress_proxy_size}}
spec:
  rules:
  - host: app.{{.ingress_dns_name}}
    http:
      paths:
      - backend:
          serviceName: app
          servicePort: 80
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{.kube_namespace}}
type: Opaque
data:
  JWT_SECRET: {{ .jwt_secret | b64enc }}
  PLAY_CRYPTO_SECRET: {{ .app_play_crypto_secret | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: {{.kube_namespace}}
spec:
  ports:
  - port: 80
    targetPort: 9001
  selector:
    app: app
