---
apiVersion: v1
kind: ConfigMap
metadata:
  name: campaigner-config
  namespace: {{.kube_namespace}}
data:
  BIND_PORT: '9001'
  DB_MIGRATE: 'true'
  DB_URL: jdbc:mariadb://{{ .mysql_host }}:3306/campaigner
  DB_USER: {{ .campaigner_db_user }}
  DEVICE_REGISTRY_HOST: device-registry
  DEVICE_REGISTRY_PORT: '80'
  DIRECTOR_HOST: director
  DIRECTOR_PORT: '80'
  ENV_PREFIX: {{ .env_prefix }}
  JAVA_OPTS: {{ .campaigner_java_opts }}
  REPORT_METRICS: "false"
  SCHEDULER_BATCH_SIZE: '200'
  SCHEDULER_DELAY: 10 seconds
  SCHEDULER_POLLING_TIMEOUT: 10 seconds
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: campaigner
  namespace: {{.kube_namespace}}
spec:
  selector:
    matchLabels:
      app: campaigner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: campaigner
    spec:
{{ if .gke_nodepool }}
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .gke_nodepool }}
{{ end }}
      containers:
      - name: campaigner
        image: {{ .campaigner_docker_image }}
        envFrom:
        - configMapRef:
            name: kafka-shared
        - configMapRef:
            name: campaigner-config
        - secretRef:
            name: campaigner-secret
        ports:
        - containerPort: 9001
        resources:
          requests:
            cpu: {{ .campaigner_cpu }}
            memory: {{ .campaigner_mem }}
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 30
          httpGet:
            port: 9001
            path: "/health"
---
apiVersion: v1
kind: Secret
metadata:
  name: campaigner-secret
  namespace: {{.kube_namespace}}
type: Opaque
data:
  DB_PASSWORD: {{ .campaigner_db_password | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  name: campaigner
  namespace: {{.kube_namespace}}
spec:
  ports:
  - port: 80
    targetPort: 9001
  selector:
    app: campaigner
