---
apiVersion: v1
kind: ConfigMap
metadata:
  name: device-registry-config
  namespace: {{.kube_namespace}}
data:
  AUTH_PROTOCOL: none
  BIND_HOST: 0.0.0.0
  BIND_PORT: '9001'
  DB_MIGRATE: 'true'
  DB_URL: jdbc:mariadb://{{ .mysql_host }}:3306/device_registry
  DB_USER: {{ .device_registry_db_user }}
  ENV_PREFIX: {{ .env_prefix }}
  JAVA_OPTS: {{ .device_registry_java_opts }}
  REPORT_METRICS: "false"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-registry
  namespace: {{.kube_namespace}}
spec:
  selector:
    matchLabels:
      app: device-registry
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: device-registry
    spec:
{{ if .gke_nodepool }}
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .gke_nodepool }}
{{ end }}
      containers:
      - name: device-registry
        image: {{ .device_registry_docker_image }}
        envFrom:
        - configMapRef:
            name: kafka-shared
        - configMapRef:
            name: device-registry-config
        - secretRef:
            name: device-registry-secret
        ports:
        - containerPort: 9001
        resources:
          requests:
            cpu: {{ .device_registry_cpu }}
            memory: {{ .device_registry_mem }}
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 30
          httpGet:
            port: 9001
            path: "/health"
---
apiVersion: v1
kind: Secret
metadata:
  name: device-registry-secret
  namespace: {{.kube_namespace}}
type: Opaque
data:
  DB_PASSWORD: {{ .device_registry_db_password | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  name: device-registry
  namespace: {{.kube_namespace}}
spec:
  ports:
  - port: 80
    targetPort: 9001
  selector:
    app: device-registry
