---
apiVersion: v1
kind: ConfigMap
metadata:
  name: director-config
  namespace: {{.kube_namespace}}
data:
  BIND_PORT: '9001'
  DB_MIGRATE: 'true'
  DB_URL: jdbc:mariadb://{{ .mysql_host }}:3306/director
  DB_USER: {{ .director_db_user }}
  ENV_PREFIX: {{ .env_prefix }}
  JAVA_OPTS: {{ .director_java_opts }}
  REPORT_METRICS: "false"
  SOTA_CORE_HOST: sota-core
  SOTA_CORE_PORT: '80'
  TUF_KEYSERVER_HOST: tuf-keyserver
  TUF_KEYSERVER_PORT: '80'
  TUF_REPOSERVER_HOST: tuf-reposerver
  TUF_REPOSERVER_PORT: '80'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: director
  namespace: {{.kube_namespace}}
spec:
  selector:
    matchLabels:
      app: director
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: director
    spec:
{{ if .gke_nodepool }}
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .gke_nodepool }}
{{ end }}
      containers:
      - name: director
        image: {{ .director_docker_image }}
        envFrom:
        - configMapRef:
            name: kafka-shared
        - configMapRef:
            name: director-config
        - secretRef:
            name: director-secret
        ports:
        - containerPort: 9001
        resources:
          requests:
            cpu: {{ .director_cpu }}
            memory: {{ .director_mem }}
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 30
          httpGet:
            port: 9001
            path: "/health"
---
apiVersion: v1
kind: Secret
metadata:
  name: director-secret
  namespace: {{.kube_namespace}}
type: Opaque
data:
  DB_PASSWORD: {{ .director_db_password | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  name: director
  namespace: {{.kube_namespace}}
spec:
  ports:
  - port: 80
    targetPort: 9001
  selector:
    app: director
