---
apiVersion: v1
kind: ConfigMap
metadata:
  name: director-daemon-config
  namespace: {{.kube_namespace}}
data:
  BIND_PORT: '9001'
  DB_MIGRATE: 'true'
  DB_URL: jdbc:mariadb://{{ .mysql_host }}:3306/director
  DB_USER: {{ .director_daemon_db_user }}
  ENV_PREFIX: {{ .env_prefix }}
  JAVA_OPTS: {{ .director_daemon_java_opts }}
  REPORT_METRICS: "false"
  SOTA_CORE_HOST: sota-core
  SOTA_CORE_PORT: '80'
  TUF_KEYSERVER_HOST: tuf-keyserver
  TUF_KEYSERVER_PORT: '80'
  TUF_REPOSERVER_HOST: tuf-reposerver
  TUF_REPOSERVER_PORT: '80'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: director-daemon
  namespace: {{.kube_namespace}}
spec:
  selector:
    matchLabels:
      app: director-daemon
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: director-daemon
    spec:
{{ if .gke_nodepool }}
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .gke_nodepool }}
{{ end }}
      containers:
      - name: director-daemon
        image: {{ .director_daemon_docker_image }}
        args:
        - "-main"
        - com.advancedtelematic.director.daemon.DaemonBoot
        envFrom:
        - configMapRef:
            name: kafka-shared
        - configMapRef:
            name: director-daemon-config
        - secretRef:
            name: director-daemon-secret
        ports:
        - containerPort: 9001
        resources:
          requests:
            cpu: {{ .director_daemon_cpu }}
            memory: {{ .director_daemon_mem }}
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          httpGet:
            port: 9001
            path: "/health"
---
apiVersion: v1
kind: Secret
metadata:
  name: director-daemon-secret
  namespace: {{.kube_namespace}}
type: Opaque
data:
  DB_PASSWORD: {{ .director_daemon_db_password | b64enc }}
