apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: oauthful
  namespace: {{.kube_namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauthful
  template:
    metadata:
      labels:
        app: oauthful
    spec:
{{ if .gke_nodepool }}
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .gke_nodepool }}
{{ end }}
      containers:
      - name: app
        image: opensourcefoundries/oauthful:e9d60c3
        ports:
        - containerPort: 8000
---

apiVersion: v1
kind: Service
metadata:
  name: oauthful
  namespace: {{.kube_namespace}}
spec:
  ports:
  - targetPort: 8000
    port: 80
  selector:
    app: oauthful
