---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-events-config
  namespace: {{.kube_namespace}}
data:
  AUTH_PROTOCOL: none
  AUTH_VERIFICATION: local
  BIND_HOST: 0.0.0.0
  BIND_PORT: '9001'
  ENV_PREFIX: {{ .env_prefix }}
  PACKAGES_VERSION_FORMAT: ".+"
  REPORT_METRICS: "false"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-events
  namespace: {{.kube_namespace}}
spec:
  selector:
    matchLabels:
      app: web-events
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web-events
    spec:
{{ if .gke_nodepool }}
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .gke_nodepool }}
{{ end }}
      containers:
      - image: {{ .web_events_docker_image }}
        name: web-events
        envFrom:
        - configMapRef:
            name: kafka-shared
        - configMapRef:
            name: web-events-config
        - secretRef:
            name: web-events-secret
        ports:
        - containerPort: 9001
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 30
          httpGet:
            port: 9001
            path: "/health"
        resources:
          requests:
            cpu: {{ .web_events_cpu }}
            memory: {{ .web_events_mem }}
---
{{- if .create_ingress }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-events
  namespace: {{.kube_namespace}}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/limit-whitelist: {{.ingress_acl_whitelist}}
spec:
  rules:
  - host: web-events.{{ .ingress_dns_name }}
    http:
      paths:
      - backend:
          serviceName: web-events
          servicePort: 80
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: web-events-secret
  namespace: {{.kube_namespace}}
type: Opaque
data:
  JWT_SECRET: {{ .jwt_secret | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  name: web-events
  namespace: {{.kube_namespace}}
spec:
  ports:
  - port: 80
    targetPort: 9001
  selector:
    app: web-events
